-- Disable RLS for main tables to allow unrestricted access during development
ALTER TABLE IF EXISTS materiales DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS obras DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS usuarios DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS stock_obra_material DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS entradas DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS entrada_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS salidas DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS salida_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS requerimientos DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS requerimiento_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ordenes_compra DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS orden_compra_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS solicitudes_compra DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS solicitud_compra_items DISABLE ROW LEVEL SECURITY;

-- Also disable RLS for other tables that might exist
ALTER TABLE IF EXISTS supplier_price_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS validation_results DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS report_templates DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS framework_contracts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS user_preferences DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS delivery_routes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS route_deliveries DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS import_templates DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS import_jobs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS import_errors DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS user_dashboards DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS template_instances DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS calculated_metrics DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS job_queue DISABLE ROW LEVEL SECURITY;